[package]
name = "duplicate_finder"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.7"
sha2 = "0.10"
image = "0.25.5"
indicatif = "0.17"
eframe = "0.30"
egui = "0.30"
tokio = { version = "1.42.0", features = ["full"] }
tokio-stream = "0.1.17"
futures = "0.3.31"